#!/bin/sh

# This script requires that you're a member of the acm unix group at ccis, and that you've got sudo
# privelages on acm.ccs.neu.edu.

if [ "$1" = "" ]
then
  echo "Usage: $0 user"
  echo "Where user is the username @ acm.ccs.neu.edu to deploy as."
  echo "User must be a member of the acm unix group at ccis and"
  echo "must have access and sudo priveleges on acm.ccs.neu.edu."
  exit 1
fi
echo "Deploying as $1@acm.ccs.neu.edu..."
jekyll && rsync -rvz --delete _site/ $1@acm.ccs.neu.edu:/var/www-acm/ &&
echo "Setting permissions..."
ssh -t $1@acm.ccs.neu.edu "sudo chown -R www-data:acm /var/www-acm/ && sudo chmod -R 770 /var/www-acm/"
echo "Done."