common: &common
  adapter: postgresql
  username: postgres
  password: password # from psql setup, see Postgresql

development:
  <<: *common
  database: nuacm_development

test:
  <<: *common
  database: nuacm_test

production:
  <<: *common
  database: nuacm_production